#!/bin/bash


for time in DA RT
do
    for month in $( ls $time/miso )
    do
	mv $time/miso/$month ./
	unzip $month
	for file in $( ls *.csv )
	do
	    filldb_single.py $file $time
	done
	mv $month $time/miso
	rm *.csv
    done
done